name: My-GitHubActions
env:
APPLICATION_NAME: "MyFlask"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name:Print Hello World
      run: echo Hello.world!
      run: echo Hello.world!
    
        
